version: '3.8'

volumes:
  postgres-data:
    driver: local
  pgadmin-data:

services:
  postgres:
    image: postgres
    environment:
      POSTGRES_PASSWORD: password
      POSTGRES_USER: admin
      POSTGRES_DB: rent
    volumes:
      - postgres-data:/var/lib/postgresql/data
    ports:
      - "5433:5432"
  pgadmin:
    image: dpage/pgadmin4:6.16
    environment:
      PGADMIN_DEFAULT_EMAIL: golovanshalom@gmail.com
      PGADMIN_DEFAULT_PASSWORD: password
      PGADMIN_LISTEN_PORT: 81
    ports:
      - "8082:81"
    volumes:
      - pgadmin-data:/var/lib/pgadmin
